# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: groovy

# set sudo required for non-container vm with more mem even though we don't need sudo
# https://docs.travis-ci.com/user/reference/overview/
sudo: required
dist: trusty

install:
  - git fetch --unshallow

matrix:
  include:
    - env: BC='indy' FEATURE='18' TARGET_JAVA_HOME="/home/travis/openjdk$FEATURE" LICENSE='GPL'
      jdk: openjdk16
    - env: BC='indy' FEATURE='17' TARGET_JAVA_HOME="/home/travis/openjdk$FEATURE" LICENSE='GPL'
      jdk: openjdk16
    - env: BC='indy'
      jdk: openjdk16
    - env: BC='indy'
      jdk: openjdk15
    - env: BC='indy'
      jdk: openjdk14
    - env: BC='indy'
      jdk: openjdk13
    - env: BC='indy'
      jdk: openjdk12
    - env: BC='indy'
      jdk: openjdk11
    - env: BC='indy'
      jdk: openjdk10
    - env: BC='indy'
      jdk: oraclejdk9
    - env: BC='indy'
      jdk: oraclejdk8

#    - env: BC='sonar'
#      jdk: openjdk11

before_script:
  - unset _JAVA_OPTIONS

script:
  - ./gradlew -version
  - if [ "$TARGET_JAVA_HOME" != "" ]; then wget https://github.com/sormuras/bach/raw/master/install-jdk.sh -P /tmp/ && chmod 755 /tmp/install-jdk.sh; fi
  - if [ "$TARGET_JAVA_HOME" != "" ]; then /tmp/install-jdk.sh --target "$TARGET_JAVA_HOME" --workspace "/home/travis/.cache/install-jdk" --feature "$FEATURE" --license "$LICENSE" --cacerts; fi
  - if [ "$BC" == "indy" ]; then travis_wait 60 ./gradlew test -Ptarget.java.home=$TARGET_JAVA_HOME; elif [ "$BC" == "sonar" ]; then travis_wait 60 ./gradlew sonarqube -Dsonar.login=$SONAR_LOGIN -Pcoverage=true; fi


after_failure:
  - find /home/travis/build/apache/groovy/build/reports/dependency-verification -type f -name "*.html" | xargs cat
  - ./gradlew --write-verification-metadata pgp,sha512 --dry-run
  - diff -u /home/travis/build/apache/groovy/gradle/verification-metadata.xml /home/travis/build/apache/groovy/gradle/verification-metadata.dryrun.xml